In [1]:
import pandas as pd

In [2]:
df_todo=pd.read_csv("dataset_indo.csv")
df_hotel_flight=pd.read_csv("datasetindo_hotel_flight.csv")

In [6]:
df_todo

,Unnamed: 0,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount
0,0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006
1,2,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212
2,3,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882
3,4,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495
4,5,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358
...,...,...,...,...,...,...,...
321,616,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742
322,619,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019
323,621,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343
324,627,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309
325,643,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206

In [7]:
df_todo=df_todo.drop("Unnamed: 0", axis=1)

In [5]:
df_hotel_flight=df_hotel_flight.drop("Unnamed: 0", axis=1)

In [4]:
df_hotel_flight

,Unnamed: 0,Travel Destination,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,0,Bintan,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,1,Seminyak,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,2,Bali,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,3,Ubud,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,4,Jakarta,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,NaN
...,...,...,...,...,...,...
317,20,Toyapakeh,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
318,21,Singakerta,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
319,22,Guwang,NaN,NaN,NaN,NaN
320,23,Singapadu Kaler,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
321,24,Batu Karas,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [8]:
tes=pd.merge(df_todo, df_hotel_flight, on="Travel Destination")

dropping all duplications

In [9]:
tes=tes.drop_duplicates(subset="Travel Destination", keep="first")

In [11]:
tes

,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,NaN
...,...,...,...,...,...,...,...,...,...,...
325,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
326,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
327,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,NaN,NaN,NaN,NaN
328,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
329,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [12]:
tes.to_csv("dataset_indo_forhtml.csv")

In [18]:
df=pd.read_csv("dataset_indo_forhtml.csv")

In [19]:
df

,Unnamed: 0,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,1,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,2,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,3,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,4,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
315,325,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
316,326,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
317,327,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,NaN,NaN,NaN,NaN
318,328,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
319,329,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          320 non-null    int64
 1   Country Name        320 non-null    object
 2   Travel Destination  320 non-null    object
 3   Checking            320 non-null    object
 4   Things to Do        320 non-null    object
 5   location            320 non-null    object
 6   reviewcount         320 non-null    int64
 7   Hotel Link          311 non-null    object
 8   Hotel Best Deal     304 non-null    object
 9   Flight Link         311 non-null    object
 10  Flight Best Deal    186 non-null    object
dtypes: int64(2), object(9)
memory usage: 27.6+ KB

In [54]:
df[df["Hotel Link"].isnull()]

,Unnamed: 0,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
250,250,Indonesia,Celuk,Celuk,"['Tempat Belanja (5)', 'Tur (3)', 'Pemandangan...","Bali, Indonesia",176,NaN,NaN,NaN,NaN
265,265,Indonesia,Prambanan,Prambanan,"['Pemandangan & Tengara (5)', 'Tur (4)', 'Akti...","Jawa Tengah, Indonesia",6641,NaN,NaN,NaN,NaN
272,272,Indonesia,Kayuputih,Kayuputih,"['Tur (2)', 'Aktivitas Luar Ruangan (2)', 'Tra...","Sukasada, Indonesia",432,NaN,NaN,NaN,NaN
282,282,Indonesia,Imogiri,Imogiri,"['Wisata Alam & Taman (2)', 'Tempat Belanja (1...","Yogyakarta, Indonesia",305,NaN,NaN,NaN,NaN
284,284,Indonesia,Rinca,Rinca,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Taman Nasional Komodo, Indonesia",727,NaN,NaN,NaN,NaN
286,286,Indonesia,Sangeh,Sangeh,"['Pemandangan & Tengara (2)', 'Tempat Belanja ...","Bali, Indonesia",535,NaN,NaN,NaN,NaN
292,292,Indonesia,Manggar,Manggar,"['Pemandangan & Tengara (2)', 'Wisata Alam & T...","Pulau Belitung, Indonesia",190,NaN,NaN,NaN,NaN
305,305,Indonesia,Nungnung,Nungnung,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Bali, Indonesia",334,NaN,NaN,NaN,NaN
317,317,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,NaN,NaN,NaN,NaN

karena datanya hanya sedikit, dapat kita lakukan imputasi manual saja (tidak efektif menggunakan algoritma python untuk mendapatkan data-data yang hilang ini)

In [21]:
df.at[250,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g1592991-Celuk_Bali-Hotels.html"
df.at[250,"Hotel Best Deal"]="Rp 684.167"
df.at[250,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297694-a_airport0.JKT-a_airport1.DPS-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.21ff92a6__2D__e799__2D__48b9__2D__853e__2D__013fa661adbf__2E__5683-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Denpasar_Bali.html"
df.at[250,"Flight Best Deal"]="Rp 1.273.077"

df.at[265,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g8067878-Prambanan_Central_Java_Java-Hotels.html"
df.at[265,"Hotel Best Deal"]="Rp 937.191"
df.at[265,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g294230-a_airport0.JKT-a_airport1.JOG-a_cos.0-a_date0.20201029-a_date1.20201030-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Yogyakarta_Region_Java.html"
df.at[265,"Flight Best Deal"]="Rp 1.724.800"

df.at[272,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g11435643-Kayuputih_Sukasada_Buleleng_Regency_Bali-Hotels.html"
df.at[272,"Hotel Best Deal"]="Rp 1.239.669"
df.at[272,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297694-a_airport0.JKT-a_airport1.DPS-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.21ff92a6__2D__e799__2D__48b9__2D__853e__2D__013fa661adbf__2E__5683-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Denpasar_Bali.html"
df.at[272,"Flight Best Deal"]="Rp 1.273.077"

df.at[282,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g3333916-Imogiri_Yogyakarta_Region_Java-Hotels.html"
df.at[282,"Hotel Best Deal"]="Rp 172.702"
df.at[282,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g294230-a_airport0.JKT-a_airport1.JOG-a_cos.0-a_date0.20201029-a_date1.20201030-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Yogyakarta_Region_Java.html"
df.at[282,"Flight Best Deal"]="Rp 1.724.800"

df.at[286,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g9723252-Sangeh_Bali-Hotels.html"
df.at[286,"Hotel Best Deal"]="Rp 750.000"
df.at[286,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297694-a_airport0.JKT-a_airport1.DPS-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.21ff92a6__2D__e799__2D__48b9__2D__853e__2D__013fa661adbf__2E__5683-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Denpasar_Bali.html"
df.at[286,"Flight Best Deal"]="Rp 1.724.800"

df.at[284,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g1820452-Rinca_Komodo_National_Park_Komodo_East_Nusa_Tenggara-Hotels.html"
df.at[284,"Hotel Best Deal"]="Rp 624.732"
df.at[284,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297728-a_airport0.JKT-a_airport1.TMC-a_cos.0-a_date0.20201029-a_date1.20201030-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-East_Nusa_Tenggara.html"
df.at[284,"Flight Best Deal"]="Rp 3.763.200"

df.at[292,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g3396933-Manggar_Belitung_Island_Bangka_Belitung_Islands_Sumatra-Hotels.html"
df.at[292,"Hotel Best Deal"]="Rp 134.883"
df.at[292,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g668845-a_airport0.JKT-a_airport1.TJQ-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.88f2e0f0__2D__54ca__2D__4250__2D__b37a__2D__27975e20eb67__2E__7499-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Belitung_Island_Bangka_Belitung_Islands_Sumatra.html"
df.at[292,"Flight Best Deal"]="Rp 739.470"

df.at[305,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g9856222-Nungnung_Bali-Hotels.html"
df.at[305,"Hotel Best Deal"]="Rp 629.256"
df.at[305,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297694-a_airport0.JKT-a_airport1.DPS-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.21ff92a6__2D__e799__2D__48b9__2D__853e__2D__013fa661adbf__2E__5683-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Denpasar_Bali.html"
df.at[305,"Flight Best Deal"]="Rp 1.724.800"

df.at[317,"Hotel Link"]="https://www.tripadvisor.com/Hotels-g19140131-Guwang_Sukawati_Gianyar_Regency_Bali-Hotels.html"
df.at[317,"Hotel Best Deal"]="Rp 235.636"
df.at[317,"Flight Link"]="https://www.tripadvisor.com/CheapFlightsSearchResults-g297694-a_airport0.JKT-a_airport1.DPS-a_cos.0-a_date0.20201029-a_date1.20201030-a_formImp.21ff92a6__2D__e799__2D__48b9__2D__853e__2D__013fa661adbf__2E__5683-a_nearby0.no-a_nearby1.no-a_nonstop.no-a_pax0.a-a_travelers.1-Denpasar_Bali.html"
df.at[317,"Flight Best Deal"]="Rp 1.724.800"

checking if there is any null values remain

In [22]:
df[df["Hotel Link"].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, Country Name, Travel Destination, Checking, Things to Do, location, reviewcount, Hotel Link, Hotel Best Deal, Flight Link, Flight Best Deal]
Index: []

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          320 non-null    int64
 1   Country Name        320 non-null    object
 2   Travel Destination  320 non-null    object
 3   Checking            320 non-null    object
 4   Things to Do        320 non-null    object
 5   location            320 non-null    object
 6   reviewcount         320 non-null    int64
 7   Hotel Link          320 non-null    object
 8   Hotel Best Deal     313 non-null    object
 9   Flight Link         320 non-null    object
 10  Flight Best Deal    195 non-null    object
dtypes: int64(2), object(9)
memory usage: 27.6+ KB

In [24]:
df[df["Hotel Best Deal"].isnull()]["Hotel Link"]

142    https://www.tripadvisor.co.id/Hotels-g3400865-...
151    https://www.tripadvisor.co.id/Hotels-g2444699-...
158    https://www.tripadvisor.co.id/Hotels-g1600794-...
180    https://www.tripadvisor.co.id/Hotels-g3398689-...
193    https://www.tripadvisor.co.id/Hotels-g1600180-...
232    https://www.tripadvisor.co.id/Hotels-g3381380-...
289    https://www.tripadvisor.co.id/Hotels-g2444661-...
Name: Hotel Link, dtype: object

In [25]:
for i in df[df["Hotel Best Deal"].isnull()]["Hotel Link"]:
    print (i)

https://www.tripadvisor.co.id/Hotels-g3400865-Anambas_Islands_Riau_Islands_Province-Hotels.html
https://www.tripadvisor.co.id/Hotels-g2444699-Banda_Neira_Maluku_Islands-Hotels.html
https://www.tripadvisor.co.id/Hotels-g1600794-Alor_Island_East_Nusa_Tenggara-Hotels.html
https://www.tripadvisor.co.id/Hotels-g3398689-Payakumbuh_West_Sumatra_Sumatra-Hotels.html
https://www.tripadvisor.co.id/Hotels-g1600180-Seram_Island_Maluku_Islands-Hotels.html
https://www.tripadvisor.co.id/Hotels-g3381380-Bayah_Banten_Province_Java-Hotels.html
https://www.tripadvisor.co.id/Hotels-g2444661-Kalabahi_Alor_Island_East_Nusa_Tenggara-Hotels.html

In [26]:
df[df["Flight Best Deal"].isnull()]["location"].unique()

array(['Bintan Regency, Indonesia', 'Jawa, Indonesia',
       'Jawa Barat, Indonesia', 'Jawa Tengah, Indonesia',
       'Banten Province, Indonesia', 'Jawa Timur, Indonesia',
       'Nusa Tenggara Timur, Indonesia', 'Papua Barat, Indonesia',
       'Aceh, Indonesia', 'Sulawesi Selatan, Indonesia',
       'Kalimantan Timur, Indonesia', 'Sulawesi Tengah, Indonesia',
       'Bintan, Indonesia', 'Labuhan, Indonesia', 'Indonesia',
       'Kepulauan Bangka Belitung, Indonesia',
       'Kalimantan Tengah, Indonesia', 'Sulawesi Utara, Indonesia',
       'Yogyakarta, Indonesia', 'Riau Archipelago, Indonesia',
       'Pulau Weh, Indonesia', 'Kabupaten Karawang, Indonesia',
       'Riau, Indonesia', 'Kepulauan Maluku, Indonesia',
       'Nusa Tenggara Barat, Indonesia', 'Raja Ampat, Indonesia',
       'Bitung, Indonesia', 'Kepulauan Togian, Indonesia',
       'Sulawesi, Indonesia', 'Sumatra Selatan, Indonesia',
       'Maluku, Indonesia', 'Papua, Indonesia',
       'Kepulauan Kai, Indonesia', 'Bogor Regency, Indonesia',
       'Babakan Madang, Indonesia'], dtype=object)

In [27]:
df.to_csv("dataset_indo_forhtml.csv")

In [28]:
df=pd.read_csv("dataset_indo_forhtml.csv")

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     313 non-null    float64
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    195 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 22.6+ KB

In [137]:
null_flight=df[df["Flight Best Deal"].isnull()]["Travel Destination"].unique()

In [138]:
null_flight

array(['Bintan', 'Jakarta', 'Bogor', 'Puncak', 'Purwokerto', 'Anyer',
       'Tangerang', 'Batu', 'Garut', 'Pangandaran', 'Sumba', 'Cirebon',
       'Malang', 'Cisarua', 'Sukabumi', 'Raja Ampat', 'Lembang',
       'Tawangmangu', 'Serpong', 'Pulau Weh', 'Jepara', 'Rantepao',
       'Samarinda', 'Tegal', 'Salatiga', 'Kepulauan Togian', 'Jember',
       'Lagoi', 'Kediri', 'Jawa Barat', 'Jawa Timur', 'Situbondo',
       'Mojokerto', 'Carita', 'Pasuruan', 'Nusa Tenggara Barat',
       'Cianjur', 'Pulau Bangka', 'Pangkalan Bun', 'Bitung', 'Wonosobo',
       'Trawas', 'Prigen', 'Jawa Tengah', 'Bantul', 'Gunung Kidul',
       'Pulau Komodo', 'Pulau Karimun', 'Cilacap', 'Pacitan', 'Sidoarjo',
       'Ungaran', 'Sabang', 'Pekalongan', 'Karawang', 'Purwakarta',
       'Kepulauan Anambas', 'Cipanas', 'Temanggung', 'Baturaden',
       'Bandar Neira', 'Kebumen', 'Kudus', 'Tulungagung', 'Tomohon',
       'Pulau Moyo', 'Jombang', 'Waisai', 'Pulau Simeulue',
       'Pulau Lembeh', 'Pulau Malenge', 'Nganjuk', 'Takengon',
       'Pandeglang', 'Trenggalek', 'Pakem', 'Kaliurang', 'Sengkang',
       'Bondowoso', 'Sukapura', 'Ponorogo', 'Bojonegoro', 'Pulau Seram',
       'Sulawesi Utara', 'Pulau Pef', 'Riau Archipelago', 'Pandaan',
       'Galang', 'Purwodadi', 'Sragen', 'Ciamis', 'Kepulauan Kai',
       'Cimahi', 'Lahat', 'Teluk Bakau', 'Saparua', 'Bayah',
       'Tana Toraja', 'Purbalingga', 'Sukoharjo', 'Sentani', 'Purworejo',
       'Tual', 'Banyumas', 'Cijulang', 'Pulau Una Una', 'South Tangerang',
       'Katupat', 'Karanganyar', 'Ranowangko', 'Bintan Regency', 'Ngawi',
       'Sewon', 'Majalengka', 'Megamendung', 'Sumur Batu',
       'Babakan Madang', 'Bogor Regency', 'Gunung Kijang',
       'Pulau Kakaban', 'Mendut', 'Labuhan', 'Cihideung', 'Pulau Kri',
       'Batu Karas'], dtype=object)

In [139]:
df[df["Flight Best Deal"].isnull()]

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182.0,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
4,Indonesia,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,360563.0,https://www.tripadvisor.co.id/Flights-g294229-...,NaN
17,Indonesia,Bogor,"['Wisata Alam & Taman (42)', 'Aktivitas Luar R...","Jawa Barat, Indonesia",38424,https://www.tripadvisor.co.id/Hotels-g297706-B...,970043.0,https://www.tripadvisor.co.id/Flights-g297706-...,NaN
18,Indonesia,Puncak,"['Tur (2)', 'Pemandangan & Tengara (2)', 'Wisa...","Jawa Barat, Indonesia",8282,https://www.tripadvisor.co.id/Hotels-g844506-P...,611207.0,https://www.tripadvisor.co.id/Flights-g844506-...,NaN
25,Indonesia,Purwokerto,"['Wisata Alam & Taman (10)', 'Pemandangan & Te...","Jawa Tengah, Indonesia",3635,https://www.tripadvisor.co.id/Hotels-g790290-P...,428430.0,https://www.tripadvisor.co.id/Flights-g790290-...,NaN
...,...,...,...,...,...,...,...,...,...
296,Indonesia,Mendut,"['Tempat Belanja (2)', 'Tur (1)', 'Pemandangan...","Jawa Tengah, Indonesia",294,https://www.tripadvisor.co.id/Hotels-g3373423-...,306908.0,https://www.tripadvisor.co.id/Flights-g3373423...,NaN
306,Indonesia,Labuhan,"['Tur (7)', 'Aktivitas Luar Ruangan (7)', 'Tur...","Banten Province, Indonesia",195,https://www.tripadvisor.co.id/Hotels-g3320215-...,836621.0,https://www.tripadvisor.co.id/Flights-g3320215...,NaN
308,Indonesia,Cihideung,"['Wisata Alam & Taman (2)', 'Kebun Binatang & ...","Jawa Barat, Indonesia",171,https://www.tripadvisor.co.id/Hotels-g13219542...,119884.0,https://www.tripadvisor.co.id/Flights-g1321954...,NaN
311,Indonesia,Pulau Kri,"['Tur (4)', 'Tur dengan Perahu & Olahraga Air ...","Raja Ampat, Indonesia",131,https://www.tripadvisor.co.id/Hotels-g15024679...,578999.0,https://www.tripadvisor.co.id/Flights-g1502467...,NaN
319,Indonesia,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,208333.0,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

for places near jakarta (no need to take flight, we impute "0" as the "Flight Best Deal"

In [29]:
df["Flight Best Deal"][4]="Rp 0"
df["Flight Best Deal"][17]="Rp 0"
df["Flight Best Deal"][18]="Rp 0"
df["Flight Best Deal"][32]="Rp 0"

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [30]:
df[df["Flight Best Deal"].isnull()]

,Unnamed: 0,Unnamed: 0.1,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,0,0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
25,25,29,Indonesia,Purwokerto,Purwokerto,"['Wisata Alam & Taman (10)', 'Pemandangan & Te...","Jawa Tengah, Indonesia",3635,https://www.tripadvisor.co.id/Hotels-g790290-P...,Rp 428.430,https://www.tripadvisor.co.id/Flights-g790290-...,NaN
29,29,33,Indonesia,Anyer,Anyer,"['Wisata Alam & Taman (1)', 'Aktivitas Luar Ru...","Banten Province, Indonesia",2735,https://www.tripadvisor.co.id/Hotels-g3400871-...,Rp 668.000,https://www.tripadvisor.co.id/Flights-g3400871...,NaN
34,34,38,Indonesia,Batu,Batu,"['Wisata Alam & Taman (23)', 'Pemandangan & Te...","Jawa Timur, Indonesia",16754,https://www.tripadvisor.co.id/Hotels-g1237079-...,Rp 594.247,https://www.tripadvisor.co.id/Flights-g1237079...,NaN
35,35,39,Indonesia,Garut,Garut,"['Wisata Alam & Taman (18)', 'Aktivitas Luar R...","Jawa Barat, Indonesia",2936,https://www.tripadvisor.co.id/Hotels-g1137840-...,Rp 377.686,https://www.tripadvisor.co.id/Flights-g1137840...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
296,296,305,Indonesia,Mendut,Mendut,"['Tempat Belanja (2)', 'Tur (1)', 'Pemandangan...","Jawa Tengah, Indonesia",294,https://www.tripadvisor.co.id/Hotels-g3373423-...,Rp 306.908,https://www.tripadvisor.co.id/Flights-g3373423...,NaN
306,306,316,Indonesia,Labuhan,Labuhan,"['Tur (7)', 'Aktivitas Luar Ruangan (7)', 'Tur...","Banten Province, Indonesia",195,https://www.tripadvisor.co.id/Hotels-g3320215-...,Rp 836.621,https://www.tripadvisor.co.id/Flights-g3320215...,NaN
308,308,318,Indonesia,Cihideung,Cihideung,"['Wisata Alam & Taman (2)', 'Kebun Binatang & ...","Jawa Barat, Indonesia",171,https://www.tripadvisor.co.id/Hotels-g13219542...,Rp 119.884,https://www.tripadvisor.co.id/Flights-g1321954...,NaN
311,311,321,Indonesia,Pulau Kri,Pulau Kri,"['Tur (4)', 'Tur dengan Perahu & Olahraga Air ...","Raja Ampat, Indonesia",131,https://www.tripadvisor.co.id/Hotels-g15024679...,Rp 578.999,https://www.tripadvisor.co.id/Flights-g1502467...,NaN
319,319,329,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [142]:
for i in null_flight:
    for j in range(len(df)):
        if df["Travel Destination"][j]==i:
            print(j,i,"----",df["Flight Link"][j])

0 Bintan ---- https://www.tripadvisor.co.id/Flights-g297718-Bintan_Island_Bintan_Regency_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
4 Jakarta ---- https://www.tripadvisor.co.id/Flights-g294229-Jakarta_Java-Cheap_Discount_Airfares.html
17 Bogor ---- https://www.tripadvisor.co.id/Flights-g297706-Bogor_West_Java_Java-Cheap_Discount_Airfares.html
18 Puncak ---- https://www.tripadvisor.co.id/Flights-g844506-Puncak_West_Java_Java-Cheap_Discount_Airfares.html
25 Purwokerto ---- https://www.tripadvisor.co.id/Flights-g790290-Purwokerto_Central_Java_Java-Cheap_Discount_Airfares.html
29 Anyer ---- https://www.tripadvisor.co.id/Flights-g3400871-Anyer_Banten_Province_Java-Cheap_Discount_Airfares.html
32 Tangerang ---- https://www.tripadvisor.co.id/Flights-g1493703-Tangerang_Banten_Province_Java-Cheap_Discount_Airfares.html
34 Batu ---- https://www.tripadvisor.co.id/Flights-g1237079-Batu_East_Java_Java-Cheap_Discount_Airfares.html
35 Garut ---- https://www.tripadvisor.co.id/Flights-g1137840-Garut_West_Java_Java-Cheap_Discount_Airfares.html
36 Pangandaran ---- https://www.tripadvisor.co.id/Flights-g1137814-Pangandaran_West_Java_Java-Cheap_Discount_Airfares.html
46 Sumba ---- https://www.tripadvisor.co.id/Flights-g297731-Sumba_East_Nusa_Tenggara-Cheap_Discount_Airfares.html
47 Cirebon ---- https://www.tripadvisor.co.id/Flights-g297707-Cirebon_West_Java_Java-Cheap_Discount_Airfares.html
48 Malang ---- https://www.tripadvisor.co.id/Flights-g297710-Malang_East_Java_Java-Cheap_Discount_Airfares.html
52 Cisarua ---- https://www.tripadvisor.co.id/Flights-g644045-Cisarua_West_Java_Java-Cheap_Discount_Airfares.html
60 Sukabumi ---- https://www.tripadvisor.co.id/Flights-g297714-Sukabumi_West_Java_Java-Cheap_Discount_Airfares.html
64 Raja Ampat ---- https://www.tripadvisor.co.id/Flights-g2303999-Raja_Ampat_West_Papua-Cheap_Discount_Airfares.html
65 Lembang ---- https://www.tripadvisor.co.id/Flights-g7187358-Lembang_West_Java_Java-Cheap_Discount_Airfares.html
68 Tawangmangu ---- https://www.tripadvisor.co.id/Flights-g3175991-Tawangmangu_Central_Java_Java-Cheap_Discount_Airfares.html
71 Serpong ---- https://www.tripadvisor.co.id/Flights-g3574346-Serpong_Banten_Province_Java-Cheap_Discount_Airfares.html
72 Pulau Weh ---- https://www.tripadvisor.co.id/Flights-g1787388-Pulau_Weh_Aceh_Sumatra-Cheap_Discount_Airfares.html
74 Jepara ---- https://www.tripadvisor.co.id/Flights-g1189712-Jepara_Central_Java_Java-Cheap_Discount_Airfares.html
76 Rantepao ---- https://www.tripadvisor.co.id/Flights-g317108-Rantepao_South_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
77 Samarinda ---- https://www.tripadvisor.co.id/Flights-g317102-Samarinda_East_Kalimantan_Kalimantan-Cheap_Discount_Airfares.html
84 Tegal ---- https://www.tripadvisor.co.id/Flights-g790289-Tegal_Central_Java_Java-Cheap_Discount_Airfares.html
85 Salatiga ---- https://www.tripadvisor.co.id/Flights-g1012818-Salatiga_Central_Java_Java-Cheap_Discount_Airfares.html
86 Kepulauan Togian ---- https://www.tripadvisor.co.id/Flights-g1025046-Togian_Islands_Central_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
87 Jember ---- https://www.tripadvisor.co.id/Flights-g1052738-Jember_East_Java_Java-Cheap_Discount_Airfares.html
89 Lagoi ---- https://www.tripadvisor.co.id/Flights-g1096248-Lagoi_Bintan_Island_Bintan_Regency_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
93 Kediri ---- https://www.tripadvisor.co.id/Flights-g311297-Kediri_East_Java_Java-Cheap_Discount_Airfares.html
94 Jawa Barat ---- https://www.tripadvisor.co.id/Flights-g2301792-West_Java_Java-Cheap_Discount_Airfares.html
95 Jawa Timur ---- https://www.tripadvisor.co.id/Flights-g2301797-East_Java_Java-Cheap_Discount_Airfares.html
99 Situbondo ---- https://www.tripadvisor.co.id/Flights-g303955-Situbondo_East_Java_Java-Cheap_Discount_Airfares.html
100 Mojokerto ---- https://www.tripadvisor.co.id/Flights-g303954-Mojokerto_East_Java_Java-Cheap_Discount_Airfares.html
101 Carita ---- https://www.tripadvisor.co.id/Flights-g317104-Carita_Labuhan_Banten_Province_Java-Cheap_Discount_Airfares.html
104 Pasuruan ---- https://www.tripadvisor.co.id/Flights-g297711-Pasuruan_East_Java_Java-Cheap_Discount_Airfares.html
105 Nusa Tenggara Barat ---- https://www.tripadvisor.co.id/Flights-g297732-West_Nusa_Tenggara-Cheap_Discount_Airfares.html
106 Cianjur ---- https://www.tripadvisor.co.id/Flights-g1006216-Cianjur_West_Java_Java-Cheap_Discount_Airfares.html
107 Pulau Bangka ---- https://www.tripadvisor.co.id/Flights-g1234795-Bangka_Island_Bangka_Belitung_Islands_Sumatra-Cheap_Discount_Airfares.html
110 Pangkalan Bun ---- https://www.tripadvisor.co.id/Flights-g680187-Pangkalan_Bun_Central_Kalimantan_Kalimantan-Cheap_Discount_Airfares.html
111 Bitung ---- https://www.tripadvisor.co.id/Flights-g680020-Bitung_North_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
114 Wonosobo ---- https://www.tripadvisor.co.id/Flights-g1137818-Wonosobo_Central_Java_Java-Cheap_Discount_Airfares.html
115 Trawas ---- https://www.tripadvisor.co.id/Flights-g2698863-Trawas_East_Java_Java-Cheap_Discount_Airfares.html
116 Prigen ---- https://www.tripadvisor.co.id/Flights-g2699971-Prigen_East_Java_Java-Cheap_Discount_Airfares.html
120 Jawa Tengah ---- https://www.tripadvisor.co.id/Flights-g2301793-Central_Java_Java-Cheap_Discount_Airfares.html
121 Bantul ---- https://www.tripadvisor.co.id/Flights-g2304084-Bantul_Yogyakarta_Region_Java-Cheap_Discount_Airfares.html
122 Gunung Kidul ---- https://www.tripadvisor.co.id/Flights-g2304083-Gunung_Kidul_Java-Cheap_Discount_Airfares.html
124 Pulau Komodo ---- https://www.tripadvisor.co.id/Flights-g2311506-Komodo_East_Nusa_Tenggara-Cheap_Discount_Airfares.html
125 Pulau Karimun ---- https://www.tripadvisor.co.id/Flights-g2347651-Karimun_Island_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
126 Cilacap ---- https://www.tripadvisor.co.id/Flights-g317105-Cilacap_Central_Java_Java-Cheap_Discount_Airfares.html
129 Pacitan ---- https://www.tripadvisor.co.id/Flights-g3175993-Pacitan_East_Java_Java-Cheap_Discount_Airfares.html
131 Sidoarjo ---- https://www.tripadvisor.co.id/Flights-g3175994-Sidoarjo_East_Java_Java-Cheap_Discount_Airfares.html
133 Ungaran ---- https://www.tripadvisor.co.id/Flights-g3207850-Ungaran_Central_Java_Java-Cheap_Discount_Airfares.html
134 Sabang ---- https://www.tripadvisor.co.id/Flights-g2540440-Sabang_Pulau_Weh_Aceh_Sumatra-Cheap_Discount_Airfares.html
135 Pekalongan ---- https://www.tripadvisor.co.id/Flights-g2040542-Pekalongan_Central_Java_Java-Cheap_Discount_Airfares.html
136 Karawang ---- https://www.tripadvisor.co.id/Flights-g2048660-Karawang_Karawang_Regency_West_Java_Java-Cheap_Discount_Airfares.html
139 Purwakarta ---- https://www.tripadvisor.co.id/Flights-g1823197-Purwakarta_West_Java_Java-Cheap_Discount_Airfares.html
142 Kepulauan Anambas ---- https://www.tripadvisor.co.id/Flights-g3400865-Anambas_Islands_Riau_Islands_Province-Cheap_Discount_Airfares.html
143 Cipanas ---- https://www.tripadvisor.co.id/Flights-g5970498-Cipanas_West_Java_Java-Cheap_Discount_Airfares.html
145 Temanggung ---- https://www.tripadvisor.co.id/Flights-g3576942-Temanggung_Central_Java_Java-Cheap_Discount_Airfares.html
150 Baturaden ---- https://www.tripadvisor.co.id/Flights-g1062752-Baturaden_Central_Java_Java-Cheap_Discount_Airfares.html
151 Bandar Neira ---- https://www.tripadvisor.co.id/Flights-g2444699-Banda_Neira_Maluku_Islands-Cheap_Discount_Airfares.html
152 Kebumen ---- https://www.tripadvisor.co.id/Flights-g3576937-Kebumen_Central_Java_Java-Cheap_Discount_Airfares.html
155 Kudus ---- https://www.tripadvisor.co.id/Flights-g1966182-Kudus_Central_Java_Java-Cheap_Discount_Airfares.html
164 Tulungagung ---- https://www.tripadvisor.co.id/Flights-g3207852-Tulungagung_East_Java_Java-Cheap_Discount_Airfares.html
166 Tomohon ---- https://www.tripadvisor.co.id/Flights-g680013-Tomohon_North_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
167 Pulau Moyo ---- https://www.tripadvisor.co.id/Flights-g1820453-Moyo_Island_West_Nusa_Tenggara-Cheap_Discount_Airfares.html
168 Jombang ---- https://www.tripadvisor.co.id/Flights-g3561625-Jombang_East_Java_Java-Cheap_Discount_Airfares.html
169 Waisai ---- https://www.tripadvisor.co.id/Flights-g3632533-Waisai_Raja_Ampat_West_Papua-Cheap_Discount_Airfares.html
170 Pulau Simeulue ---- https://www.tripadvisor.co.id/Flights-g3648972-Pulau_Simeulue_Aceh_Sumatra-Cheap_Discount_Airfares.html
172 Pulau Lembeh ---- https://www.tripadvisor.co.id/Flights-g1071667-Pulau_Lembeh_Bitung_North_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html

174 Pulau Malenge ---- https://www.tripadvisor.co.id/Flights-g12834203-Malenge_Island_Togian_Islands_Central_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
177 Nganjuk ---- https://www.tripadvisor.co.id/Flights-g1472380-Nganjuk_East_Java_Java-Cheap_Discount_Airfares.html
178 Takengon ---- https://www.tripadvisor.co.id/Flights-g2373422-Takengon_Aceh_Sumatra-Cheap_Discount_Airfares.html
179 Pandeglang ---- https://www.tripadvisor.co.id/Flights-g3396006-Pandeglang_Banten_Province_Java-Cheap_Discount_Airfares.html
181 Trenggalek ---- https://www.tripadvisor.co.id/Flights-g3932216-Trenggalek_East_Java_Java-Cheap_Discount_Airfares.html
182 Pakem ---- https://www.tripadvisor.co.id/Flights-g4475689-Pakem_Yogyakarta_Region_Java-Cheap_Discount_Airfares.html
183 Kaliurang ---- https://www.tripadvisor.co.id/Flights-g2698839-Kaliurang_Central_Java_Java-Cheap_Discount_Airfares.html
184 Sengkang ---- https://www.tripadvisor.co.id/Flights-g3178762-Sengkang_South_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
186 Bondowoso ---- https://www.tripadvisor.co.id/Flights-g3200172-Bondowoso_East_Java_Java-Cheap_Discount_Airfares.html
188 Sukapura ---- https://www.tripadvisor.co.id/Flights-g3199127-Sukapura_East_Java_Java-Cheap_Discount_Airfares.html
189 Ponorogo ---- https://www.tripadvisor.co.id/Flights-g2654170-Ponorogo_East_Java_Java-Cheap_Discount_Airfares.html
190 Bojonegoro ---- https://www.tripadvisor.co.id/Flights-g3733889-Bojonegoro_East_Java_Java-Cheap_Discount_Airfares.html
193 Pulau Seram ---- https://www.tripadvisor.co.id/Flights-g1600180-Seram_Island_Maluku_Islands-Cheap_Discount_Airfares.html
194 Sulawesi Utara ---- https://www.tripadvisor.co.id/Flights-g2301803-North_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
205 Pulau Pef ---- https://www.tripadvisor.co.id/Flights-g2690061-Pulau_Pef_Raja_Ampat_West_Papua-Cheap_Discount_Airfares.html
206 Riau Archipelago ---- https://www.tripadvisor.co.id/Flights-g2347741-Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
209 Pandaan ---- https://www.tripadvisor.co.id/Flights-g3185086-Pandaan_East_Java_Java-Cheap_Discount_Airfares.html
213 Galang ---- https://www.tripadvisor.co.id/Flights-g3359611-Galang_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
214 Purwodadi ---- https://www.tripadvisor.co.id/Flights-g3389996-Purwodadi_Central_Java_Java-Cheap_Discount_Airfares.html
218 Sragen ---- https://www.tripadvisor.co.id/Flights-g3312574-Sragen_Central_Java_Java-Cheap_Discount_Airfares.html
219 Ciamis ---- https://www.tripadvisor.co.id/Flights-g3310650-Ciamis_West_Java_Java-Cheap_Discount_Airfares.html
222 Kepulauan Kai ---- https://www.tripadvisor.co.id/Flights-g3334605-Kai_Islands_Maluku_Islands-Cheap_Discount_Airfares.html
223 Cimahi ---- https://www.tripadvisor.co.id/Flights-g1784984-Cimahi_West_Java_Java-Cheap_Discount_Airfares.html
226 Lahat ---- https://www.tripadvisor.co.id/Flights-g1233750-Lahat_South_Sumatra_Sumatra-Cheap_Discount_Airfares.html
228 Teluk Bakau ---- https://www.tripadvisor.co.id/Flights-g3223519-Telukbakau_Bintan_Island_Bintan_Regency_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
230 Saparua ---- https://www.tripadvisor.co.id/Flights-g3793647-Saparua_Maluku_Maluku_Islands-Cheap_Discount_Airfares.html
232 Bayah ---- https://www.tripadvisor.co.id/Flights-g3381380-Bayah_Banten_Province_Java-Cheap_Discount_Airfares.html
236 Tana Toraja ---- https://www.tripadvisor.co.id/Flights-g8838499-Tana_Toraja_South_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
238 Purbalingga ---- https://www.tripadvisor.co.id/Flights-g6215328-Purbalingga_Central_Java_Java-Cheap_Discount_Airfares.html
239 Sukoharjo ---- https://www.tripadvisor.co.id/Flights-g6368992-Sukoharjo_Central_Java_Java-Cheap_Discount_Airfares.html
241 Sentani ---- https://www.tripadvisor.co.id/Flights-g6208762-Sentani_Papua-Cheap_Discount_Airfares.html
242 Purworejo ---- https://www.tripadvisor.co.id/Flights-g6215339-Purworejo_Central_Java_Java-Cheap_Discount_Airfares.html
243 Tual ---- https://www.tripadvisor.co.id/Flights-g6592999-Tual_Kai_Islands_Maluku_Islands-Cheap_Discount_Airfares.html
246 Banyumas ---- https://www.tripadvisor.co.id/Flights-g6502019-Banyumas_Central_Java_Java-Cheap_Discount_Airfares.html
251 Cijulang ---- https://www.tripadvisor.co.id/Flights-g1773315-Cijulang_West_Java_Java-Cheap_Discount_Airfares.html
255 Pulau Una Una ---- https://www.tripadvisor.co.id/Flights-g12719069-Una_Una_Island_Togian_Islands_Central_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
256 South Tangerang ---- https://www.tripadvisor.co.id/Flights-g12719085-South_Tangerang_Banten_Province_Java-Cheap_Discount_Airfares.html
257 Katupat ---- https://www.tripadvisor.co.id/Flights-g12719055-Katupat_Togian_Islands_Central_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
258 Karanganyar ---- https://www.tripadvisor.co.id/Flights-g12564917-Karanganyar_Central_Java_Java-Cheap_Discount_Airfares.html
261 Ranowangko ---- https://www.tripadvisor.co.id/Flights-g12700479-Ranowangko_North_Sulawesi_Sulawesi-Cheap_Discount_Airfares.html
262 Bintan Regency ---- https://www.tripadvisor.co.id/Flights-g12811408-Bintan_Regency_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
268 Ngawi ---- https://www.tripadvisor.co.id/Flights-g8300003-Ngawi_East_Java_Java-Cheap_Discount_Airfares.html
269 Sewon ---- https://www.tripadvisor.co.id/Flights-g4283430-Sewon_Yogyakarta_Region_Java-Cheap_Discount_Airfares.html
270 Majalengka ---- https://www.tripadvisor.co.id/Flights-g6487157-Majalengka_West_Java_Java-Cheap_Discount_Airfares.html
273 Megamendung ---- https://www.tripadvisor.co.id/Flights-g12033986-Megamendung_Bogor_Regency_West_Java_Java-Cheap_Discount_Airfares.html
274 Sumur Batu ---- https://www.tripadvisor.co.id/Flights-g12388634-Sumur_Batu_Babakan_Madang_Bogor_Regency_West_Java_Java-Cheap_Discount_Airfares.html
275 Babakan Madang ---- https://www.tripadvisor.co.id/Flights-g12388629-Babakan_Madang_Bogor_Regency_West_Java_Java-Cheap_Discount_Airfares.html
276 Bogor Regency ---- https://www.tripadvisor.co.id/Flights-g12388606-Bogor_Regency_West_Java_Java-Cheap_Discount_Airfares.html
278 Gunung Kijang ---- https://www.tripadvisor.co.id/Flights-g12119576-Gunung_Kijang_Bintan_Island_Bintan_Regency_Riau_Archipelago_Riau_Islands_Province-Cheap_Discount_Airfares.html
290 Pulau Kakaban ---- https://www.tripadvisor.co.id/Flights-g3346467-Pulau_Kakaban_East_Kalimantan_Kalimantan-Cheap_Discount_Airfares.html
296 Mendut ---- https://www.tripadvisor.co.id/Flights-g3373423-Mendut_Central_Java_Java-Cheap_Discount_Airfares.html
306 Labuhan ---- https://www.tripadvisor.co.id/Flights-g3320215-Labuhan_Banten_Province_Java-Cheap_Discount_Airfares.html
308 Cihideung ---- https://www.tripadvisor.co.id/Flights-g13219542-Cihideung_West_Java_Java-Cheap_Discount_Airfares.html
311 Pulau Kri ---- https://www.tripadvisor.co.id/Flights-g15024679-Kri_Island_Raja_Ampat_West_Papua-Cheap_Discount_Airfares.html
319 Batu Karas ---- https://www.tripadvisor.co.id/Flights-g6677749-Batu_Karas_West_Java_Java-Cheap_Discount_Airfares.html

manual imputation

In [31]:
df["Flight Best Deal"][36]="Rp 0"
df["Flight Best Deal"][46]="Rp 3.113.200"
df["Flight Best Deal"][47]="Rp 0"
df["Flight Best Deal"][48]="Rp 857.217"
df["Flight Best Deal"][52]="Rp 0"
df["Flight Best Deal"][60]="Rp 0"
df["Flight Best Deal"][65]="Rp 0"
df["Flight Best Deal"][71]="Rp 0"
df["Flight Best Deal"][72]="Rp 3.269.374"
df["Flight Best Deal"][76]="Rp 3.039.298"
df["Flight Best Deal"][87]="Rp 2.311.390"
df["Flight Best Deal"][107]="Rp 1.201.700"
df["Flight Best Deal"][124]="Rp 3.741.300"
df["Flight Best Deal"][134]="Rp 3.269.374"
df["Flight Best Deal"][136]="Rp 0"
df["Flight Best Deal"][139]="Rp 0"
df["Flight Best Deal"][182]="Rp 1.724.800"
df["Flight Best Deal"][184]="Rp 4.460.849"
df["Flight Best Deal"][223]="Rp 0"
df["Flight Best Deal"][311]="Rp 4.339.113"
df["Flight Best Deal"][256]="Rp 0"
df["Flight Best Deal"][269]="Rp 2.875.300"
df["Flight Best Deal"][273]="Rp 0"
df["Flight Best Deal"][274]="Rp 0"
df["Flight Best Deal"][276]="Rp 0"
df["Flight Best Deal"][290]="Rp 3.708.400"

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [32]:
df[df["Flight Best Deal"].isnull()]

,Unnamed: 0,Unnamed: 0.1,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,0,0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
25,25,29,Indonesia,Purwokerto,Purwokerto,"['Wisata Alam & Taman (10)', 'Pemandangan & Te...","Jawa Tengah, Indonesia",3635,https://www.tripadvisor.co.id/Hotels-g790290-P...,Rp 428.430,https://www.tripadvisor.co.id/Flights-g790290-...,NaN
29,29,33,Indonesia,Anyer,Anyer,"['Wisata Alam & Taman (1)', 'Aktivitas Luar Ru...","Banten Province, Indonesia",2735,https://www.tripadvisor.co.id/Hotels-g3400871-...,Rp 668.000,https://www.tripadvisor.co.id/Flights-g3400871...,NaN
34,34,38,Indonesia,Batu,Batu,"['Wisata Alam & Taman (23)', 'Pemandangan & Te...","Jawa Timur, Indonesia",16754,https://www.tripadvisor.co.id/Hotels-g1237079-...,Rp 594.247,https://www.tripadvisor.co.id/Flights-g1237079...,NaN
35,35,39,Indonesia,Garut,Garut,"['Wisata Alam & Taman (18)', 'Aktivitas Luar R...","Jawa Barat, Indonesia",2936,https://www.tripadvisor.co.id/Hotels-g1137840-...,Rp 377.686,https://www.tripadvisor.co.id/Flights-g1137840...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
278,278,287,Indonesia,Gunung Kijang,Gunung Kijang,"['Tur (1)', 'Pemandangan & Tengara (1)', 'Tur ...","Bintan, Indonesia",364,https://www.tripadvisor.co.id/Hotels-g12119576...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g1211957...,NaN
296,296,305,Indonesia,Mendut,Mendut,"['Tempat Belanja (2)', 'Tur (1)', 'Pemandangan...","Jawa Tengah, Indonesia",294,https://www.tripadvisor.co.id/Hotels-g3373423-...,Rp 306.908,https://www.tripadvisor.co.id/Flights-g3373423...,NaN
306,306,316,Indonesia,Labuhan,Labuhan,"['Tur (7)', 'Aktivitas Luar Ruangan (7)', 'Tur...","Banten Province, Indonesia",195,https://www.tripadvisor.co.id/Hotels-g3320215-...,Rp 836.621,https://www.tripadvisor.co.id/Flights-g3320215...,NaN
308,308,318,Indonesia,Cihideung,Cihideung,"['Wisata Alam & Taman (2)', 'Kebun Binatang & ...","Jawa Barat, Indonesia",171,https://www.tripadvisor.co.id/Hotels-g13219542...,Rp 119.884,https://www.tripadvisor.co.id/Flights-g1321954...,NaN
319,319,329,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [33]:
df.to_csv("dataset_indo_forhtml.csv")

In [36]:
df=df.drop(["Unnamed: 0", "Unnamed: 0.1"], axis=1)

In [37]:
df

,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,Rp 0
...,...,...,...,...,...,...,...,...,...,...
315,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
316,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
317,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,https://www.tripadvisor.com/Hotels-g19140131-G...,Rp 235.636,https://www.tripadvisor.com/CheapFlightsSearch...,Rp 1.724.800
318,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
319,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [15]:
df["Hotel Best Deal"][0][3:]

'1.740.182'

In [38]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].str[3:]

In [39]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].str.replace(".","")

In [40]:
df["Flight Best Deal"]=df["Flight Best Deal"].str[3:]

In [41]:
df["Flight Best Deal"]=df["Flight Best Deal"].str.replace(".","")

In [44]:
df=df.drop("Checking", axis=1)

In [45]:
df

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,2331874,https://www.tripadvisor.co.id/Flights-g469404-...,1305700
2,Indonesia,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,656190,https://www.tripadvisor.co.id/Flights-g294226-...,1145870
3,Indonesia,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,2865927,https://www.tripadvisor.co.id/Flights-g297701-...,1145870
4,Indonesia,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,360563,https://www.tripadvisor.co.id/Flights-g294229-...,0
...,...,...,...,...,...,...,...,...,...
315,Indonesia,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,663636,https://www.tripadvisor.co.id/Flights-g1411558...,1752927
316,Indonesia,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,661107,https://www.tripadvisor.co.id/Flights-g1588060...,1752927
317,Indonesia,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,https://www.tripadvisor.com/Hotels-g19140131-G...,235636,https://www.tripadvisor.com/CheapFlightsSearch...,1724800
318,Indonesia,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,627097,https://www.tripadvisor.co.id/Flights-g2011686...,1197735
319,Indonesia,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,208333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [47]:
df.to_csv("dataset_indo_redi.csv",index=False)

In [58]:
df=pd.read_csv("dataset_indo_forhtml.csv")

In [59]:
df

,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,Rp 0
...,...,...,...,...,...,...,...,...,...,...
315,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
316,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
317,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,https://www.tripadvisor.com/Hotels-g19140131-G...,Rp 235.636,https://www.tripadvisor.com/CheapFlightsSearch...,Rp 1.724.800
318,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
319,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Checking            320 non-null    object
 3   Things to Do        320 non-null    object
 4   location            320 non-null    object
 5   reviewcount         320 non-null    int64
 6   Hotel Link          320 non-null    object
 7   Hotel Best Deal     313 non-null    object
 8   Flight Link         320 non-null    object
 9   Flight Best Deal    225 non-null    object
dtypes: int64(1), object(9)
memory usage: 25.1+ KB

In [62]:
df[df["Hotel Best Deal"].isnull()]

,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
142,Indonesia,Kepulauan Anambas,Kepulauan Anambas,"['Wisata Alam & Taman (4)', 'Harga terjangkau ...","Riau, Indonesia",221,https://www.tripadvisor.co.id/Hotels-g3400865-...,NaN,https://www.tripadvisor.co.id/Flights-g3400865...,NaN
151,Indonesia,Bandar Neira,Bandar Neira,"['Pemandangan & Tengara (5)', 'Tur (2)', 'Tur ...","Kepulauan Maluku, Indonesia",721,https://www.tripadvisor.co.id/Hotels-g2444699-...,NaN,https://www.tripadvisor.co.id/Flights-g2444699...,NaN
158,Indonesia,Alor,Alor,"['Aktivitas Luar Ruangan (7)', 'Tur (6)', 'Tur...","Nusa Tenggara Timur, Indonesia",684,https://www.tripadvisor.co.id/Hotels-g1600794-...,NaN,https://www.tripadvisor.co.id/Flights-g1600794...,Rp 6.306.742
180,Indonesia,Payakumbuh,Payakumbuh,"['Pemandangan & Tengara (4)', 'Wisata Alam & T...","West Sumatra, Indonesia",498,https://www.tripadvisor.co.id/Hotels-g3398689-...,NaN,https://www.tripadvisor.co.id/Flights-g3398689...,Rp 1.581.040
193,Indonesia,Pulau Seram,Pulau Seram,"['Wisata Alam & Taman (6)', 'Aktivitas Luar Ru...","Kepulauan Maluku, Indonesia",134,https://www.tripadvisor.co.id/Hotels-g1600180-...,NaN,https://www.tripadvisor.co.id/Flights-g1600180...,NaN
232,Indonesia,Bayah,Bayah,"['Aktivitas Luar Ruangan (2)', 'Wisata Alam & ...","Banten Province, Indonesia",207,https://www.tripadvisor.co.id/Hotels-g3381380-...,NaN,https://www.tripadvisor.co.id/Flights-g3381380...,NaN
289,Indonesia,Kalabahi,Kalabahi,"['Aktivitas Luar Ruangan (3)', 'Tur (2)', 'Tur...","Alor, Indonesia",189,https://www.tripadvisor.co.id/Hotels-g2444661-...,NaN,https://www.tripadvisor.co.id/Flights-g2444661...,Rp 6.044.192

In [63]:
df["Flight Best Deal"][142]="Rp 1.368.300"
df["Hotel Best Deal"][142]="Rp 785.375"

df["Hotel Best Deal"][151]="Rp 270.000"
df["Flight Best Deal"][151]="Rp 3.616.700"

df["Hotel Best Deal"][158]="Rp 469.495"

df["Hotel Best Deal"][180]="Rp 259.497"

df["Hotel Best Deal"][193]="Rp 361.466"
df["Flight Best Deal"][193]="Rp 3.616.700"

df["Hotel Best Deal"][232]="Rp 469.697"
df["Flight Best Deal"][232]="Rp 0"

df["Hotel Best Deal"][289]="Rp 469.495"

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Checking            320 non-null    object
 3   Things to Do        320 non-null    object
 4   location            320 non-null    object
 5   reviewcount         320 non-null    int64
 6   Hotel Link          320 non-null    object
 7   Hotel Best Deal     320 non-null    object
 8   Flight Link         320 non-null    object
 9   Flight Best Deal    229 non-null    object
dtypes: int64(1), object(9)
memory usage: 25.1+ KB

In [95]:
df.to_csv("dataset_indo_forhtml.csv", index=False)

In [96]:
pd.read_csv("dataset_indo_forhtml.csv")

,Country Name,Travel Destination,Checking,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,Rp 1.740.182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,Rp 2.331.874,https://www.tripadvisor.co.id/Flights-g469404-...,Rp 1.305.700
2,Indonesia,Bali,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,Rp 656.190,https://www.tripadvisor.co.id/Flights-g294226-...,Rp 1.145.870
3,Indonesia,Ubud,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,Rp 2.865.927,https://www.tripadvisor.co.id/Flights-g297701-...,Rp 1.145.870
4,Indonesia,Jakarta,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,Rp 360.563,https://www.tripadvisor.co.id/Flights-g294229-...,Rp 0
...,...,...,...,...,...,...,...,...,...,...
315,Indonesia,Toyapakeh,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,Rp 663.636,https://www.tripadvisor.co.id/Flights-g1411558...,Rp 1.752.927
316,Indonesia,Singakerta,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,Rp 661.107,https://www.tripadvisor.co.id/Flights-g1588060...,Rp 1.752.927
317,Indonesia,Guwang,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,https://www.tripadvisor.com/Hotels-g19140131-G...,Rp 235.636,https://www.tripadvisor.com/CheapFlightsSearch...,Rp 1.724.800
318,Indonesia,Singapadu Kaler,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,Rp 627.097,https://www.tripadvisor.co.id/Flights-g2011686...,Rp 1.197.735
319,Indonesia,Batu Karas,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,Rp 208.333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Checking            320 non-null    object
 3   Things to Do        320 non-null    object
 4   location            320 non-null    object
 5   reviewcount         320 non-null    int64
 6   Hotel Link          320 non-null    object
 7   Hotel Best Deal     320 non-null    object
 8   Flight Link         320 non-null    object
 9   Flight Best Deal    229 non-null    object
dtypes: int64(1), object(9)
memory usage: 25.1+ KB

### Formatting Hotel and Flight Best Deal

We will first reformat the hotel and flight price data into int for filling up the rest of Flight null values. Why I do this will be clear soon as we go through the notebook.

In [98]:
df["Hotel Best Deal"][0][3:]

'1.740.182'

In [99]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].str[3:]

In [100]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].str.replace(".","")

In [101]:
df["Flight Best Deal"]=df["Flight Best Deal"].str[3:]

In [102]:
df["Flight Best Deal"]=df["Flight Best Deal"].str.replace(".","")

In [104]:
df=df.drop("Checking", axis=1)

In [105]:
df

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
1,Indonesia,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,2331874,https://www.tripadvisor.co.id/Flights-g469404-...,1305700
2,Indonesia,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,656190,https://www.tripadvisor.co.id/Flights-g294226-...,1145870
3,Indonesia,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,2865927,https://www.tripadvisor.co.id/Flights-g297701-...,1145870
4,Indonesia,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,360563,https://www.tripadvisor.co.id/Flights-g294229-...,0
...,...,...,...,...,...,...,...,...,...
315,Indonesia,Toyapakeh,"['Tur (5)', 'Tur dengan Perahu & Olahraga Air ...","Nusa Penida, Indonesia",742,https://www.tripadvisor.co.id/Hotels-g14115586...,663636,https://www.tripadvisor.co.id/Flights-g1411558...,1752927
316,Indonesia,Singakerta,"['Spa & Kebugaran (2)', 'Tur (2)', 'Kursus & S...","Ubud, Indonesia",2019,https://www.tripadvisor.co.id/Hotels-g15880600...,661107,https://www.tripadvisor.co.id/Flights-g1588060...,1752927
317,Indonesia,Guwang,"['Wisata Alam & Taman (1)', 'Cocok untuk Pasan...","Sukawati, Indonesia",343,https://www.tripadvisor.com/Hotels-g19140131-G...,235636,https://www.tripadvisor.com/CheapFlightsSearch...,1724800
318,Indonesia,Singapadu Kaler,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Sukawati, Indonesia",309,https://www.tripadvisor.co.id/Hotels-g20116867...,627097,https://www.tripadvisor.co.id/Flights-g2011686...,1197735
319,Indonesia,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,208333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [106]:
df.to_csv("dataset_indo_redi.csv",index=False)

In [111]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].astype("int")

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     320 non-null    int32
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    229 non-null    object
dtypes: int32(1), int64(1), object(7)
memory usage: 21.4+ KB

we will first slice the dataframe for only the not-null flights. I will then fill out the null values using the mean of the Flight Best Deal from the available data, with first group by their location. This is why I need to change them into int first so I can calculate the mean.

In [124]:
notnull_flight=df[df["Flight Best Deal"].notnull()]

In [126]:
notnull_flight["Flight Best Deal"]=notnull_flight["Flight Best Deal"].astype("int")

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [131]:
location_data=notnull_flight.groupby("location").mean()

In [132]:
location_data

                            reviewcount  Hotel Best Deal  Flight Best Deal
location
Abang, Indonesia           53876.000000     4.950000e+05      1.145870e+06
Aceh, Indonesia             4617.500000     4.138400e+05      3.048287e+06
Alor, Indonesia              189.000000     4.694950e+05      6.044192e+06
Babakan Madang, Indonesia    904.000000     1.647934e+06      0.000000e+00
Bali, Indonesia            95475.037037     1.195130e+06      1.349385e+06
...                                 ...              ...               ...
Tejakula, Indonesia          716.000000     9.523200e+05      1.300650e+06
Timor Barat, Indonesia      2160.000000     8.175760e+05      3.764228e+06
Ubud, Indonesia             4964.500000     2.399330e+06      1.349296e+06
West Sumatra, Indonesia     2088.000000     3.679962e+05      1.276954e+06
Yogyakarta, Indonesia        539.714286     3.739274e+05      2.080386e+06

[87 rows x 3 columns]

In [153]:
null_flight=df[df["Flight Best Deal"].isnull()]

In [154]:
null_flight

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
25,Indonesia,Purwokerto,"['Wisata Alam & Taman (10)', 'Pemandangan & Te...","Jawa Tengah, Indonesia",3635,https://www.tripadvisor.co.id/Hotels-g790290-P...,428430,https://www.tripadvisor.co.id/Flights-g790290-...,NaN
29,Indonesia,Anyer,"['Wisata Alam & Taman (1)', 'Aktivitas Luar Ru...","Banten Province, Indonesia",2735,https://www.tripadvisor.co.id/Hotels-g3400871-...,668000,https://www.tripadvisor.co.id/Flights-g3400871...,NaN
34,Indonesia,Batu,"['Wisata Alam & Taman (23)', 'Pemandangan & Te...","Jawa Timur, Indonesia",16754,https://www.tripadvisor.co.id/Hotels-g1237079-...,594247,https://www.tripadvisor.co.id/Flights-g1237079...,NaN
35,Indonesia,Garut,"['Wisata Alam & Taman (18)', 'Aktivitas Luar R...","Jawa Barat, Indonesia",2936,https://www.tripadvisor.co.id/Hotels-g1137840-...,377686,https://www.tripadvisor.co.id/Flights-g1137840...,NaN
...,...,...,...,...,...,...,...,...,...
278,Indonesia,Gunung Kijang,"['Tur (1)', 'Pemandangan & Tengara (1)', 'Tur ...","Bintan, Indonesia",364,https://www.tripadvisor.co.id/Hotels-g12119576...,1740182,https://www.tripadvisor.co.id/Flights-g1211957...,NaN
296,Indonesia,Mendut,"['Tempat Belanja (2)', 'Tur (1)', 'Pemandangan...","Jawa Tengah, Indonesia",294,https://www.tripadvisor.co.id/Hotels-g3373423-...,306908,https://www.tripadvisor.co.id/Flights-g3373423...,NaN
306,Indonesia,Labuhan,"['Tur (7)', 'Aktivitas Luar Ruangan (7)', 'Tur...","Banten Province, Indonesia",195,https://www.tripadvisor.co.id/Hotels-g3320215-...,836621,https://www.tripadvisor.co.id/Flights-g3320215...,NaN
308,Indonesia,Cihideung,"['Wisata Alam & Taman (2)', 'Kebun Binatang & ...","Jawa Barat, Indonesia",171,https://www.tripadvisor.co.id/Hotels-g13219542...,119884,https://www.tripadvisor.co.id/Flights-g1321954...,NaN
319,Indonesia,Batu Karas,"['Tur (2)', 'Tur dengan Perahu & Olahraga Air ...","Jawa Barat, Indonesia",206,https://www.tripadvisor.co.id/Hotels-g6677749-...,208333,https://www.tripadvisor.co.id/Flights-g6677749...,NaN

In [158]:
for i in null_flight.index:
    if null_flight["location"][i] in location_data.index:
        df["Flight Best Deal"][i]=location_data.loc[df["location"][i]]["Flight Best Deal"]

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [159]:
null_flight.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        91 non-null     object
 1   Travel Destination  91 non-null     object
 2   Things to Do        91 non-null     object
 3   location            91 non-null     object
 4   reviewcount         91 non-null     int64
 5   Hotel Link          91 non-null     object
 6   Hotel Best Deal     91 non-null     int32
 7   Flight Link         91 non-null     object
 8   Flight Best Deal    83 non-null     object
dtypes: int32(1), int64(1), object(7)
memory usage: 9.3+ KB

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     320 non-null    int32
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    312 non-null    object
dtypes: int32(1), int64(1), object(7)
memory usage: 21.4+ KB

In [163]:
df[df["Flight Best Deal"].isnull()]

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182,https://www.tripadvisor.co.id/Flights-g297718-...,NaN
101,Indonesia,Carita,"['Tur (6)', 'Aktivitas Luar Ruangan (6)', 'Tur...","Labuhan, Indonesia",188,https://www.tripadvisor.co.id/Hotels-g317104-C...,1307247,https://www.tripadvisor.co.id/Flights-g317104-...,NaN
172,Indonesia,Pulau Lembeh,"['Wisata Alam & Taman (2)', 'Pemandangan & Ten...","Bitung, Indonesia",1484,https://www.tripadvisor.co.id/Hotels-g1071667-...,875000,https://www.tripadvisor.co.id/Flights-g1071667...,NaN
174,Indonesia,Pulau Malenge,"['Tur (2)', 'Aktivitas Luar Ruangan (2)', 'Tur...","Kepulauan Togian, Indonesia",331,https://www.tripadvisor.co.id/Hotels-g12834203...,700000,https://www.tripadvisor.co.id/Flights-g1283420...,NaN
230,Indonesia,Saparua,"['Pemandangan & Tengara (2)', 'Aktivitas Luar ...","Maluku, Indonesia",138,https://www.tripadvisor.co.id/Hotels-g3793647-...,743802,https://www.tripadvisor.co.id/Flights-g3793647...,NaN
243,Indonesia,Tual,"['Wisata Alam & Taman (3)', 'Aktivitas Luar Ru...","Kepulauan Kai, Indonesia",214,https://www.tripadvisor.co.id/Hotels-g6592999-...,295455,https://www.tripadvisor.co.id/Flights-g6592999...,NaN
255,Indonesia,Pulau Una Una,"['Tur (1)', 'Tur dengan Perahu & Olahraga Air ...","Kepulauan Togian, Indonesia",340,https://www.tripadvisor.co.id/Hotels-g12719069...,766667,https://www.tripadvisor.co.id/Flights-g1271906...,NaN
257,Indonesia,Katupat,"['Wisata Alam & Taman (3)', 'Aktivitas Luar Ru...","Kepulauan Togian, Indonesia",168,https://www.tripadvisor.co.id/Hotels-g12719055...,318182,https://www.tripadvisor.co.id/Flights-g1271905...,NaN

now, we have reduced quite a lot of null values to only 8 null values left and we can manully fill the NaN values by checking the real supposed flight price

In [164]:
df["Flight Best Deal"][0]=1048200

df["Flight Best Deal"][101]=0

df["Flight Best Deal"][172]=2590400

df["Flight Best Deal"][174]=2276400

df["Flight Best Deal"][230]=3693700

df["Flight Best Deal"][243]=3693700

df["Flight Best Deal"][255]=2276400

df["Flight Best Deal"][257]=2276400

C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\chiri\anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [167]:
df["Flight Best Deal"]=df["Flight Best Deal"].astype(int)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     320 non-null    int32
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    320 non-null    int32
dtypes: int32(2), int64(1), object(6)
memory usage: 20.1+ KB

In [169]:
df.to_csv("dataset_indo_redi.csv", index=False)

In [170]:
df.describe()

        reviewcount  Hotel Best Deal  Flight Best Deal
count  3.200000e+02     3.200000e+02      3.200000e+02
mean   3.694844e+04     8.599874e+05      1.744194e+06
std    1.903758e+05     1.301072e+06      1.407973e+06
min    1.040000e+02     1.063130e+05      0.000000e+00
25%    3.332500e+02     2.888635e+05      1.121048e+06
50%    1.485000e+03     5.003880e+05      1.305700e+06
75%    9.158500e+03     9.433748e+05      1.762479e+06
max    2.998882e+06     1.593223e+07      9.152495e+06

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     320 non-null    int32
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    320 non-null    int32
dtypes: int32(2), int64(1), object(6)
memory usage: 20.1+ KB

In [173]:
df.head()

,Country Name,Travel Destination,Things to Do,location,reviewcount,Hotel Link,Hotel Best Deal,Flight Link,Flight Best Deal
0,Indonesia,Bintan,"['Tur (39)', 'Aktivitas Luar Ruangan (30)', 'T...","Bintan Regency, Indonesia",25006,https://www.tripadvisor.co.id/Hotels-g297718-B...,1740182,https://www.tripadvisor.co.id/Flights-g297718-...,1048200
1,Indonesia,Seminyak,"['Tur (204)', 'Spa & Kebugaran (164)', 'Aktivi...","Kecamatan Kuta, Indonesia",451212,https://www.tripadvisor.co.id/Hotels-g469404-S...,2331874,https://www.tripadvisor.co.id/Flights-g469404-...,1305700
2,Indonesia,Bali,"['Tur (5.854)', 'Aktivitas Luar Ruangan (3.740...",Indonesia,2998882,https://www.tripadvisor.co.id/Hotels-g294226-B...,656190,https://www.tripadvisor.co.id/Flights-g294226-...,1145870
3,Indonesia,Ubud,"['Tur (884)', 'Aktivitas Luar Ruangan (525)', ...","Gianyar Regency, Indonesia",610495,https://www.tripadvisor.co.id/Hotels-g297701-U...,2865927,https://www.tripadvisor.co.id/Flights-g297701-...,1145870
4,Indonesia,Jakarta,"['Tur (168)', 'Tempat Belanja (148)', 'Spa & K...","Jawa, Indonesia",339358,https://www.tripadvisor.co.id/Hotels-g294229-J...,360563,https://www.tripadvisor.co.id/Flights-g294229-...,0

In [187]:
df["Hotel Best Deal"]=df["Hotel Best Deal"].astype(str)
df["Flight Best Deal"]=df["Flight Best Deal"].astype(str)

In [205]:
def rupiah_hotel(x):
    if (len(x["Hotel Best Deal"])<=6)&(len(x["Hotel Best Deal"])>3):
        return x["Hotel Best Deal"][:-3]+"."+x["Hotel Best Deal"][-3:]
    elif len(x["Hotel Best Deal"])>=7:
        return x["Hotel Best Deal"][:-6]+"."+x["Hotel Best Deal"][-6:-3]+"."+x["Hotel Best Deal"][-3:]
    else:
        return x["Hotel Best Deal"]

In [210]:
df["Hotel Best Deal"]=df.apply(rupiah_hotel,axis=1)

In [207]:
def rupiah_flight(x):
    if (len(x["Flight Best Deal"])<=6)&(len(x["Flight Best Deal"])>3):
        return x["Flight Best Deal"][:-3]+"."+x["Flight Best Deal"][-3:]
    elif len(x["Flight Best Deal"])>=7:
        return x["Flight Best Deal"][:-6]+"."+x["Flight Best Deal"][-6:-3]+"."+x["Flight Best Deal"][-3:]
    else:
        return x["Flight Best Deal"]

In [211]:
df["Flight Best Deal"]=df.apply(rupiah_flight,axis=1)

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country Name        320 non-null    object
 1   Travel Destination  320 non-null    object
 2   Things to Do        320 non-null    object
 3   location            320 non-null    object
 4   reviewcount         320 non-null    int64
 5   Hotel Link          320 non-null    object
 6   Hotel Best Deal     320 non-null    object
 7   Flight Link         320 non-null    object
 8   Flight Best Deal    320 non-null    object
dtypes: int64(1), object(8)
memory usage: 22.6+ KB

In [217]:
df["Hotel Best Deal"]="Rp "+df["Hotel Best Deal"]+",-"
df["Flight Best Deal"]="Rp "+df["Flight Best Deal"]+",-"

In [218]:
df.to_csv("dataset_indo_forhtml.csv", index=False)